version: '3.1'
services:
  database:
    image: mariadb
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - 3306:3306

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

volumes:
  dbdata:
